spring:
  application:
    name: oauth-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 1
    host: 59.110.240.170
    port: 6379
    pool:
    max-active: 20
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.1.150:3306/hd_auth?characterEncoding=utf8&useSSL=false
     username: root
     password: 123456
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://192.168.1.103:7075
  sleuth:
    sampler:
      probability: 1.0

jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

client:
  id: oauth-server
  secret: 123456
  token-header: x-client-token
  expire: 14400
  rsa-secret: x2318^^(*WRYQWR(QW&T

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.112:7070/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path:  /actuator/health
server:
  port: 7071


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false


hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1startWith


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

